import datetime

species = [
    {'id': 1, 'species_type': 'Human'},
    {'id': 2, 'species_type': 'Driod'},
    {'id': 3, 'species_type': 'Wookie'},
    {'id': 4, 'species_type': 'Rodian'},
    {'id': 5, 'species_type': 'Hutt'},
    {'id': 6, 'species_type': "Yoda's Species"},
    {'id': 7, 'species_type': 'Trandoshan'},
    {'id': 8, 'species_type': 'Mon Calamari'},
    {'id': 9, 'species_type': 'Ewok'},
    {'id': 10, 'species_type': 'Sullustan'},
    {'id': 11, 'species_type': 'Neimodian'},
    {'id': 12, 'species_type': 'Gungan'},
    {'id': 13, 'species_type': 'Toydarian'},
    {'id': 14, 'species_type': 'Dug'},
    {'id': 15, 'species_type': "Twi'lek"},
    {'id': 16, 'species_type': 'Aleena'},
    {'id': 17, 'species_type': 'Vulptereen'},
    {'id': 18, 'species_type': 'Xexto'},
    {'id': 19, 'species_type': 'Toong'},
    {'id': 20, 'species_type': 'Cerean'},
    {'id': 21, 'species_type': 'Nautolan'},
    {'id': 22, 'species_type': 'Zabrak'},
    {'id': 23, 'species_type': 'Tholothian'},
    {'id': 24, 'species_type': 'Iktotchi'},
    {'id': 25, 'species_type': 'Quermian'},
    {'id': 26, 'species_type': 'Kel Dor'},
    {'id': 27, 'species_type': 'Chagrian'},
    {'id': 28, 'species_type': 'Geonosian'},
    {'id': 29, 'species_type': 'Mirialan'},
    {'id': 30, 'species_type': 'Clawdite'},
    {'id': 31, 'species_type': 'Besalisk'},
    {'id': 32, 'species_type': 'Kaminoan'},
    {'id': 33, 'species_type': 'Skakoan'},
    {'id': 34, 'species_type': 'Muun'},
    {'id': 35, 'species_type': 'Togruta'},
    {'id': 36, 'species_type': 'Kaleesh'},
    {'id': 37, 'species_type': "Pau'an"}
]
ship_types = [
    {'id': 2, 'type_name': 'CR90 Corvette', 'starship_class': 'Star Cruiser', 'manufacturer': 'Corellian Engineering Company', 'model': 'CR90 Corvette', 'hyperdrive_rating': 2.0, 'mglt': 60, 'length': 150,
     'crew': 30, 'passenger': 600, 'cargo': 3000000, 'consumables': '1 year', 'cost_credits': 3500000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/02.jpg', 'unique': False},
    {'id': 3, 'type_name': 'Star Destroyer', 'starship_class': 'Star Dreadnought', 'manufacturer': 'Kuat Drive Yard', 'model': 'Imperial I-class Star Destroyer', 'hyperdrive_rating': 2.0, 'mglt': 60, 'length': 1600,
     'crew': 47060, 'passenger': 0, 'cargo': 36000000, 'consumables': '2 years', 'cost_credits': 150000000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/03.jpg', 'unique': False},
    {'id': 5, 'type_name': 'Sentinel-class Landing Craft', 'starship_class': 'Transport', 'manufacturer': 'Sienar Fleet Systems', 'model': 'Sentinel-class Landing Craft', 'hyperdrive_rating': 1.0, 'mglt': 70, 'length': 38,
     'crew': 5, 'passenger': 75, 'cargo': 180000, 'consumables': '1 month', 'cost_credits': 240000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/05.jpg', 'unique': False},
    {'id': 9, 'type_name': 'Death Star', 'starship_class': 'Star Dreadnought', 'manufacturer': 'Sienar Fleet System', 'model': 'D5-1 Orbital Battle Station', 'hyperdrive_rating': 4.0, 'mglt': 10, 'length': 120000,
     'crew': 342953, 'passenger': 843342, 'cargo': 1000000000000, 'consumables': '3 years', 'cost_credits': 1000000000000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/09.jpg', 'unique': True},
    {'id': 10, 'type_name': 'Millennium Falcon', 'starship_class': 'Freighter', 'manufacturer': 'Corellian Engineering Corporation', 'model': 'YT-1300 Light Freighter', 'hyperdrive_rating': 0.5, 'mglt': 75, 'length': 35,
     'crew': 4, 'passenger': 6, 'cargo': 100000, 'consumables': '2 months', 'cost_credits': 100000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/10.jpg', 'unique': True},
    {'id': 11, 'type_name': 'Y-wing', 'starship_class': 'Starfighter', 'manufacturer': 'Koensayr Manufacturing', 'model': 'BTL Y-wing', 'hyperdrive_rating': 1.0, 'mglt': 80, 'length': 14,
     'crew': 2, 'passenger': 0, 'cargo': 110, 'consumables': '1 week', 'cost_credits': 134999, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/11.jpg', 'unique': False},
    {'id': 12, 'type_name': 'X-wing', 'starship_class': 'Starfighter', 'manufacturer': 'Incom Corporation', 'model': 'T-65 X-wing', 'hyperdrive_rating': 1.0, 'mglt': 100, 'length': 13,
     'crew': 1, 'passenger': 0, 'cargo': 110, 'consumables': '1 week', 'cost_credits': 149999, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/12.jpg', 'unique': False},
    {'id': 13, 'type_name': 'TIE Advanced x1', 'starship_class': 'Starfighter', 'manufacturer': 'Sienar Fleet System', 'model': 'Twin Ion Engine Advanced x1', 'hyperdrive_rating': 1.0, 'mglt': 105, 'length': 9,
     'crew': 1, 'passenger': 0, 'cargo': 150, 'consumables': '5 days', 'cost_credits': 79999, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/13.jpg', 'unique': False},
    {'id': 14, 'type_name': "Darth Vader's TIE Fighter", 'starship_class': 'Starfighter', 'manufacturer': 'Sienar Fleet System', 'model': 'Experimental Twin Engine Advnced x2', 'hyperdrive_rating': 1.0, 'mglt': 105, 'length': 10,
     'crew': 1, 'passenger': 0, 'cargo': 150, 'consumables': '5 days', 'cost_credits': 135999, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/14.jpg', 'unique': True},
    {'id': 15, 'type_name': 'Executor', 'starship_class': 'Star Dreadnought', 'manufacturer': 'Kuat Drive Yard', 'model': 'Executor-class Star Dreadnought', 'hyperdrive_rating': 2.0, 'mglt': 40, 'length': 19000,
     'crew': 279144, 'passenger': 38000, 'cargo': 250000000, 'consumables': '6 years', 'cost_credits': 1143350000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/15.jpg', 'unique': True},
    {'id': 17, 'type_name': 'Rebel Transport', 'starship_class': 'Transport', 'manufacturer': 'Gallofree Yards, Inc.', 'model': 'GR-75 Medium Transport', 'hyperdrive_rating': 4.0, 'mglt': 20, 'length': 90,
     'crew': 6, 'passenger': 90, 'cargo': 19000000, 'consumables': '6 months', 'cost_credits': 180000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/17.jpg', 'unique': False},
    {'id': 19, 'type_name': 'ARC-170 Starfighter', 'starship_class': 'Starfighter', 'manufacturer': 'Incom Corporation', 'model': 'ARC-170 Aggressive Reconnaissance Starfighter', 'hyperdrive_rating': 1.5, 'mglt': 70, 'length': 13,
     'crew': 3, 'passenger': 0, 'cargo': 250, 'consumables': '1 month', 'cost_credits': 180000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/19.jpg', 'unique': False},
    {'id': 21, 'type_name': 'Slave 1', 'starship_class': 'Transport', 'manufacturer': 'Kuat Systems Engineering', 'model': 'Firespray-31-class Patroll and Attack', 'hyperdrive_rating': 3.0, 'mglt': 70, 'length': 22,
     'crew': 1, 'passenger': 6, 'cargo': 70000, 'consumables': '1 month', 'cost_credits': 343000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/21.jpg', 'unique': True},
    {'id': 22, 'type_name': 'Imperial Shuttle', 'starship_class': 'Transport', 'manufacturer': 'Sienar Fleet Systems', 'model': 'Lambda-Class T-4a Shuttle', 'hyperdrive_rating': 1.0, 'mglt': 50, 'length': 20,
     'crew': 6, 'passenger': 20, 'cargo': 80000, 'consumables': '2 months', 'cost_credits': 240000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/22.jpg', 'unique': False},
    {'id': 23, 'type_name': 'EF76 Nebulon-9 Escort Frigate', 'starship_class': 'Star Cruiser', 'manufacturer': 'Kuat Drive Yards', 'model': 'EF76 Nebulon-9 Escort Frigate', 'hyperdrive_rating': 2.0, 'mglt': 40, 'length': 300,
     'crew': 854, 'passenger': 75, 'cargo': 6000000, 'consumables': '2 years', 'cost_credits': 8500000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/23.jpg', 'unique': False},
    {'id': 27, 'type_name': 'Calamari Cruiser', 'starship_class': 'Star Cruiser', 'manufacturer': 'Mon Calamari Shipyards', 'model': 'MC80 Liberty Type Star Cruiser', 'hyperdrive_rating': 1.0, 'mglt': 60, 'length': 1200,
     'crew': 5400, 'passenger': 1200, 'cargo': 3000000, 'consumables': '2 years', 'cost_credits': 104000000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/27.jpg', 'unique': False},
    {'id': 28, 'type_name': 'A-wing', 'starship_class': 'Starfighter', 'manufacturer': 'Alliance Underground Engineering', 'model': 'RZ-I A-wing Interceptor', 'hyperdrive_rating': 1.0, 'mglt': 120, 'length': 10,
     'crew': 1, 'passenger': 0, 'cargo': 40, 'consumables': '1 week', 'cost_credits': 175000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/28.jpg', 'unique': False},
    {'id': 29, 'type_name': 'B-wing', 'starship_class': 'Starfighter', 'manufacturer': 'Slayn & Korpil', 'model': 'A/SF-01 B-wing Starfighter', 'hyperdrive_rating': 2.0, 'mglt': 91, 'length': 17,
     'crew': 1, 'passenger': 0, 'cargo': 45, 'consumables': '1 week', 'cost_credits': 220000, 'ship_image': 'https: // starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/29.jpg', 'unique': False},
    {'id': 30, 'type_name': 'U-wing', 'starship_class': 'Starfighter', 'manufacturer': 'Incom Corporation', 'model': 'UT-60D U-wing Starfighter', 'hyperdrive_rating': 1.0, 'mglt': 95, 'length': 24,
     'crew': 2, 'passenger': 8, 'cargo': 25000, 'consumables': '2 weeks', 'cost_credits': 130000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/30.jpg', 'unique': False},
    {'id': 31, 'type_name': 'Republic Frigate', 'starship_class': 'Star Cruiser', 'manufacturer': 'Corellian Engineering Corporation', 'model': 'Consular-Class Cruiser', 'hyperdrive_rating': 2.0, 'mglt': 60, 'length': 115,
     'crew': 9, 'passenger': 16, 'cargo': 120000, 'consumables': '3 months', 'cost_credits': 850000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/31.jpg', 'unique': False},
    {'id': 33, 'type_name': 'Imperial Zeta-Class Cargo Shuttle', 'starship_class': 'Freighter', 'manufacturer': 'Sienar Fleet Systems', 'model': 'Zeta-Class Cargo Shuttle', 'hyperdrive_rating': 2.0, 'mglt': 60, 'length': 35,
     'crew': 2, 'passenger': 20, 'cargo': 450000, 'consumables': '2 weeks', 'cost_credits': 195000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/33.jpg', 'unique': False},
    {'id': 39, 'type_name': 'Naboo Fighter', 'starship_class': 'Starfighter', 'manufacturer': 'Theed Palace Space Vessel Engineering Corps.', 'model': 'N-1 Starfighter', 'hyperdrive_rating': 1.0, 'mglt': 90, 'length': 11,
     'crew': 1, 'passenger': 0, 'cargo': 65, 'consumables': '1 week', 'cost_credits': 200000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/39.jpg', 'unique': False},
    {'id': 40, 'type_name': 'Naboo Royal Starship', 'starship_class': 'Transport', 'manufacturer': 'Theed palace Space Vessel Engineering Corps.', 'model': 'J-type 327 Nubian Royal Starship', 'hyperdrive_rating': 1.8, 'mglt': 95, 'length': 76,
     'crew': 8, 'passenger': 20, 'cargo': 30000, 'consumables': '1 month', 'cost_credits': 535000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/40.jpg', 'unique': False},
    {'id': 41, 'type_name': 'Scimitar', 'starship_class': 'Transport', 'manufacturer': 'Sienar Fleet Systems', 'model': 'Star Courier', 'hyperdrive_rating': 1.5, 'mglt': 75, 'length': 27,
     'crew': 1, 'passenger': 6, 'cargo': 250000, 'consumables': '1 month', 'cost_credits': 5500000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/41.jpg', 'unique': False},
    {'id': 43, 'type_name': 'J-Type Diplomatic Shuttle', 'starship_class': 'Transport', 'manufacturer': 'Theed palace Space Vessel Engineering Corps.', 'model': 'J-Type Diplomatic Shuttle', 'hyperdrive_rating': 0.7, 'mglt': 50, 'length': 39,
     'crew': 5, 'passenger': 10, 'cargo': 175000, 'consumables': '1 year', 'cost_credits': 2000000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/43.jpg', 'unique': False},
    {'id': 47, 'type_name': 'AA-9 Coruscant Freighter', 'starship_class': 'Freighter', 'manufacturer': 'Botajef Shipyards', 'model': 'Botajef AA-9 Freighter-Liner', 'hyperdrive_rating': 0.5, 'mglt': 50, 'length': 390,
     'crew': 15, 'passenger': 30000, 'cargo': 750000, 'consumables': '3 months', 'cost_credits': 825700, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/47.jpg', 'unique': False},
    {'id': 48, 'type_name': 'Jedi Starfighter', 'starship_class': 'Starfighter', 'manufacturer': 'Kuat Systems Engineering', 'model': 'Delta-7 Aethersprite-class Interceptor', 'hyperdrive_rating': 1.0, 'mglt': 95, 'length': 8,
     'crew': 1, 'passenger': 0, 'cargo': 60, 'consumables': '1 week', 'cost_credits': 180000, 'ship_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/starships/48.jpg', 'unique': False}
]

starships = [
    {'ship_type': 10, 'custom_name': None, 'sale_price': 1000000, 'lightyears_traveled': 24999, 'owner': 14, 'for_sale': True,
        'seller_comment': "The ship that made the Kessel Run in 12 parsecs!", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 9, 'custom_name': None, 'sale_price': 1000000000000, 'lightyears_traveled': 5, 'owner': 12, 'for_sale': True,
     'seller_comment': "Low Mileage!  Slightly used, great for destroying planets and rebel bases.  WARNING Keep Skywalkers away from exhaust ports!", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 48, 'custom_name': "Obe-Wan's Jedi Starfighter", 'sale_price': 220000, 'lightyears_traveled': 57899, 'owner': 10, 'for_sale': True,
     'seller_comment': "Ship priced to move ASAP! Need credits fast to head to Alderaan with Luke!  Spent many years burried in the sands of Tatooine, sand everywhere...", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 14, 'custom_name': None, 'sale_price': 119999, 'lightyears_traveled': 67899, 'owner': 4, 'for_sale': True,
        'seller_comment': "The Emperor is buying me a new TIE Fighter, need to sell this one.  Serious inquiries only. No rebel scum please", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 27, 'custom_name': "Home 1", 'sale_price': 100000000, 'lightyears_traveled': 124995, 'owner': 27, 'for_sale': True,
        'seller_comment': "It's a trap!  No price should be this low for a ship this great!", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 21, 'custom_name': "Boba Fett's Ship", 'sale_price': 249999, 'lightyears_traveled': 24587, 'owner': 22, 'for_sale': True,
        'seller_comment': "Great ship for hunting down Jedis or smugglers named Solo", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 12, 'custom_name': "Lauretta", 'sale_price': 105000, 'lightyears_traveled': 350950, 'owner': 18, 'for_sale': True,
        'seller_comment': 'Used X-wing fighter for sale, needs new hyperdrive, cockpit smells like Wookie...', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 3, 'custom_name': "Star Destroyer #127", 'sale_price': 12000000, 'lightyears_traveled': 157000, 'owner': 21, 'for_sale': True,
        'seller_comment': 'I have so many Star Destroyers, this one no longer pleases me.', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 22, 'custom_name': "Imperial Shuttle #291", 'sale_price': 143000, 'lightyears_traveled': 251000, 'owner': 14, 'for_sale': True,
        'seller_comment': 'Won this from a Corellian Trader in a game of sabacc...  Its no Millenium Falcon so its up for sale!', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 15, 'custom_name': "Vader's Capital Ship", 'sale_price': 750000000, 'lightyears_traveled': 150000, 'owner': 4, 'for_sale': True,
        'seller_comment': 'But it while you can, it may crash into the second Death Star one day and explode, who knows?', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 47, 'custom_name': "Rebel Freighter", 'sale_price': 620000, 'lightyears_traveled': 430000, 'owner': 25, 'for_sale': True,
     'seller_comment': 'This ship is no "Falcon" but I lost that ship in a card game to Han Solo... It will make the Kessel Run in 34 parsecs!', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 33, 'custom_name': "Imperial Cargo Ship", 'sale_price': 165000, 'lightyears_traveled': 148005, 'owner': 24,
        'for_sale': True, 'seller_comment': 'Great cargo ship, smells like Bantha...', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 41, 'custom_name': "Imperial transport ship", 'sale_price': 3120000, 'lightyears_traveled': 224725, 'owner': 17,
     'for_sale': True, 'seller_comment': 'Need to sell, this ship has too much leg room for me...', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 2, 'custom_name': "Tantive IV", 'sale_price': 1734000, 'lightyears_traveled': 425000, 'owner': 5, 'for_sale': True,
        'seller_comment': "It's been in my family for years, I don't know if I can part with it, for under 1,700,000 credits...", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 23, 'custom_name': "Nebulon Escort Frigate", 'sale_price': 3999000, 'lightyears_traveled': 625000, 'owner': 31,
     'for_sale': True, 'seller_comment': "Don't tell the Rebellion I have one of these ships for sale!", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 30, 'custom_name': "UT-60D U-wing", 'sale_price': 120000, 'lightyears_traveled': 215999, 'owner': 9, 'for_sale': True,
     'seller_comment': "I don't think Cassain is coming back for his ship... Make me an offer!", 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 5, 'custom_name': "Imperial Landing Craft", 'sale_price': 100000, 'lightyears_traveled': 255999, 'owner': 30, 'for_sale': True,
        'seller_comment': 'They just left this behind after blowing up the death star, anyone want it?', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 40, 'custom_name': "Naboo Transport W-2", 'sale_price': 370000, 'lightyears_traveled': 182575, 'owner': 33,
     'for_sale': True, 'seller_comment': 'Ahhh NUBIAN!  I give you great price!', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 19, 'custom_name': "ARC Hornet", 'sale_price': 145000, 'lightyears_traveled': 190500, 'owner': 29,
     'for_sale': True, 'seller_comment': 'Floats like a butterfly, stings like a HORNET!', 'post_date': datetime.datetime.now().isoformat()},
    {'ship_type': 28, 'custom_name': "A-wing Model 2", 'sale_price': 50000, 'lightyears_traveled': 65000, 'owner': 28, 'for_sale': True,
     'seller_comment': "Great opportunity for an Imperial to own some Rebel Tech! (It's really made out of cardboard.)", 'post_date': datetime.datetime.now().isoformat()}
]

users = [
    {'name': 'Luke Skywalker', 'email': 'lukeskywalker@aol.com', 'password': 'force1', 'species': 1, 'bio': 'Luke Skywalker was a Tatooine farm boy who rose from humble beginnings to become one of the greatest Jedi the galaxy has ever known.',
     'faction': True, 'credits': 1000000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/01.jpg', "force_points": 0},
    {'name': 'C-3PO', 'email': 'goldguy@gmail.com', 'password': 'masterluke', 'species': 2, 'bio': 'C-3PO longs for more peaceful times, but his continued service to the Resistance — and his knowledge of more than seven million forms of communication — keeps the worry-prone droid in the frontlines of galactic conflict.',
     'faction': True, 'credits': 1000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/02.jpg', "force_points": 0},
    {'name': 'R2-D2', 'email': 'droid1@R2D2.net', 'password': 'xwingsrule4', 'species': 2, 'bio': 'A reliable and versatile astromech droid, R2-D2 has served Padmé Amidala, Anakin Skywalker, and Luke Skywalker in turn, showing great bravery in rescuing his masters and their friends from many perils',
     'faction': True, 'credits': 1000000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/03.jpg', "force_points": 0},
    {'name': 'Darth Vader', 'email': 'darkside4life@hotmail.com', 'password': 'iamyourfather', 'species': 1, 'bio': 'Once a heroic Jedi Knight, Darth Vader was seduced by the dark side of the Force, became a Sith Lord, and led the Empire’s eradication of the Jedi Order. But there was still good in him…',
     'faction': False, 'credits': 1500000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/04.jpg', "force_points": 0},
    {'name': 'Leia Organa', 'email': 'goldenbikini@mac.com', 'password': 'ewoksarecute', 'species': 1, 'bio': 'Princess Leia Organa was one of the greatest leaders of the Rebel Alliance, fearless on the battlefield and dedicated to ending the Empire’s tyranny. Daughter of Padmé Amidala and Anakin Skywalker, sister of Luke Skywalker, and with a soft spot for scoundrels, Leia ranked among the galaxy’s great heroes.',
     'faction': False, 'credits': 3000000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/05.jpg', "force_points": 0},
    {'name': 'Owen Lars', 'email': 'larsevaporators@tatooine.org', 'password': 'evaporators', 'species': 1, 'bio': "Owen Lars continued his father Cliegg’s efforts to build his homestead into a productive farm, working alongside his wife, Beru. Helping with the dreary chores required to keep the farm profitable, Owen relied on his nephew Luke Skywalker. He could not rein in Luke's drive for adventure, though.",
     'faction': True, 'credits': 50000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/06.jpg', "force_points": 0},
    {'name': 'Beru Whitesun Lars', 'email': 'auntberu@optimium.net', 'password': 'larssmells', 'species': 1, 'bio': "As a young, shy girl, Beru Whitesun's aspirations did not reach beyond Tatooine. She was content to marry Owen Lars and lead the tough life of a moisture farmer.",
     'faction': True, 'credits': 25000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/07.jpg', "force_points": 0},
    {'name': 'R5-D4', 'email': 'wishiwasr2d2@R2D2.net', 'password': 'notr2d2', 'species': 2, 'bio': "A red astromech droid, R5-D4 thought he'd found a home when the Jawas sold him to Owen Lars, along with the protocol droid C-3PO. But R5's motivator blew as he rolled away from the sandcrawler, forcing the Jawas to take him back in exchange for R2-D2.",
     'faction': True, 'credits': 15000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/08.jpg', "force_points": 0},
    {'name': 'Biggs Darklighter', 'email': 'biggs@rebels.com', 'password': 'imbiggs', 'species': 1, 'bio': "Biggs Darklighter grew up on Tatooine with Luke Skywalker, and shared his friend's dreams of escaping the dull desert world. After graduating from the Imperial Academy, he defected from the Empire's service to join the Rebellion.",
     'faction': True, 'credits': 34560, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/09.jpg', "force_points": 0},
    {'name': 'Obi-Wan Kenobi', 'email': 'force2@force.net', 'password': 'usetheforceluke', 'species': 1, 'bio': "A legendary Jedi Master, Obi-Wan Kenobi was a noble man and gifted in the ways of the Force. He trained Anakin Skywalker, served as a general in the Republic Army during the Clone Wars, and guided Luke Skywalker as a mentor.",
     'faction': True, 'credits': 1000000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/10.jpg', "force_points": 0},
    {'name': 'Anakin Skywalker', 'email': 'anny1@jediturnedsith.org', 'password': 'imreallyvader', 'species': 1, 'bio': "Discovered as a slave on Tatooine by Qui-Gon Jinn and Obi-Wan Kenobi, Anakin Skywalker had the potential to become one of the most powerful Jedi ever, and was believed by some to be the prophesied Chosen One who would bring balance to the Force.",
     'faction': True, 'credits': 65000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/11.jpg', "force_points": 0},
    {'name': 'Wilhuff Tarkin', 'email': 'moftarkin@empirerulez.com', 'password': 'deathstar1', 'species': 1, 'bio': "An ambitious, ruthless proponent of military power, Wilhuff Tarkin became a favorite of Supreme Chancellor Palpatine and rose rapidly through the Imperial ranks. Shortly after the Empire's creation, he was put in charge of the construction of the Death Star. ",
     'faction': False, 'credits': 2000000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/12.jpg', "force_points": 0},
    {'name': 'Chewbacca', 'email': 'chewie@falcon.com', 'password': 'wookie1', 'species': 3, 'bio': "A legendary Wookiee warrior and Han Solo’s longtime co-pilot, Chewbacca continues to serve as faithful first mate to carry out daring missions against the First Order behind the controls of the Millennium Falcon. Known as Chewie to his closest friends, he was part of a core group of rebels who restored freedom to the galaxy during the reign of the Galactic Empire. ",
     'faction': True, 'credits': 500000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/13.jpg', "force_points": 0},
    {'name': 'Han Solo', 'email': 'solo1@falcon.com', 'password': '12parsecs', 'species': 1, 'bio': "Han Solo rose from an impoverished childhood on the mean streets of Corellia to become one of the heroes of the Rebel Alliance. As captain of the Millennium Falcon, Han and his co-pilot Chewbacca came to believe in the cause of galactic freedom, joining Luke Skywalker and Princess Leia Organa in the fight against the Empire.",
     'faction': True, 'credits': 25000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/14.jpg', "force_points": 0},
    {'name': 'Greedo', 'email': 'greedo@bountyhunters.org', 'password': 'hanshotme', 'species': 4, 'bio': "Greedo was a Rodian bounty hunter with a tapir-like snout, bulbous eyes, pea-green skin, and a crest of spines atop his skull. He was overzealous and a bit slow on the take, not to mention a pretty poor shot with a blaster. ",
     'faction': False, 'credits': 125000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/15.jpg', "force_points": 0},
    {'name': 'Jabba Desilijic Tiure', 'email': 'jabba@hutt.net', 'password': 'iwillgetyousolo', 'species': 5, 'bio': "Jabba the Hutt was one of the galaxy’s most powerful gangsters, with far-reaching influence in both politics and the criminal underworld.",
     'faction': False, 'credits': 7500000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/16.jpg', "force_points": 0},
    {'name': 'Darth Maul', 'email': 'darthmaul@jediturnedsith.org', 'password': 'jediscum', 'species': 23, 'bio': "A deadly, agile Sith Lord trained by the evil Darth Sidious, Darth Maul was a formidable warrior and scheming mastermind. He wielded an intimidating double-bladed lightsaber and fought with a menacing ferocity. ",
     'faction': False, 'credits': 143000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/17.jpg', "force_points": 0},
    {'name': 'Wedge Antilles', 'email': 'wedge2@rebels.com', 'password': 'wedgethis', 'species': 1, 'bio': "A talented young rebel pilot from Corellia, Wedge Antilles survived the attack on the first Death Star to become a respected veteran of Rogue Squadron.",
     'faction': True, 'credits': 132500, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/18.jpg', "force_points": 0},
    {'name': 'Jek Tono Porkins', 'email': 'jek@rebels.com', 'password': 'vaderkilledme', 'species': 1, 'bio': "Jek Tono Porkins, nicknamed 'Piggy', was a male human trader and pilot from Bestine IV. He decided to abandon his homeworld after the Galactic Empire moved in and built a new military base there, and he ended up joining the Alliance to Restore the Republic.",
     'faction': True, 'credits': 5000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/19.jpg', "force_points": 0},
    {'name': 'Yoda', 'email': 'yoda@force.net', 'password': 'thereisnotry', 'species': 6, 'bio': "Yoda was a legendary Jedi Master and stronger than most in his connection with the Force. Small in size but wise and powerful, he trained Jedi for over 800 years, playing integral roles in the Clone Wars, the instruction of Luke Skywalker, and unlocking the path to immortality.",
     'faction': True, 'credits': 10000000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/20.jpg', "force_points": 0},
    {'name': 'Palpatine', 'email': 'emperor@jediturnedsith.org', 'password': 'darkside', 'species': 1, 'bio': "The dark side of the Force is a pathway to many abilities some consider to be unnatural, and Sheev Palpatine is the most infamous follower of its doctrines. Scheming, powerful, and evil to the core, Darth Sidious restored the Sith and destroyed the Jedi Order. Living a double life, he was also Palpatine, a Naboo Senator and phantom menace",
     'faction': False, 'credits': 1000000000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/21.jpg', "force_points": 0},
    {'name': 'Boba Fett', 'email': 'bfett@bountyhunters.org', 'password': '', 'species': 1, 'bio': "With his customized Mandalorian armor, deadly weaponry, and silent demeanor, Boba Fett was one of the most feared bounty hunters in the galaxy. A genetic clone of his “father,” bounty hunter Jango Fett, Boba learned combat and martial skills from a young age.",
     'faction': False, 'credits': 750000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/22.jpg', "force_points": 0},
    {'name': 'IG-88', 'email': 'IG@R2D2.net', 'password': 'imdroid', 'species': 2, 'bio': "IG-88 is a battered chrome war droid who has become a bounty hunter, and answered Darth Vader's call to capture the Millennium Falcon during the events surrounding the Battle of Hoth.",
     'faction': False, 'credits': 50000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/23.jpg', "force_points": 0},
    {'name': 'Bossk', 'email': 'bossk@bountyhunters.org', 'password': 'bossk1', 'species': 7, 'bio': "One of the most feared bounty hunters of the galaxy, Bossk used his natural Trandoshan hunting instincts to capture his prey. During the Clone Wars, the red-eyed reptilian partnered with Aurra Sing, Castas and young Boba Fett. Bossk didn't care much for vendettas or politics. He was in it to get paid. After a brief stint in a Republic prison, Bossk continued his partnership with Fett, becoming a bodyguard to the teen bounty hunter.",
     'faction': False, 'credits': 500000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/24.jpg', "force_points": 0},
    {'name': 'Lando Calrissian', 'email': 'lando@falcon.com', 'password': 'cloudcity', 'species': 1, 'bio': "Lando Calrissian may have come late to the fight against the Empire, but his role in destroying the second Death Star cemented his reputation as a hero. After he lost his beloved ship to Han Solo, Lando spent years living the high life and pursuing get-rich-quick schemes, with uneven results. He went semi-respectable as the baron administrator of Cloud City, only to be drawn into the fight against the Empire. ",
     'faction': True, 'credits': 3000000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/25.jpg', "force_points": 0},
    {'name': 'Lobot', 'email': 'lobot@cloudcity.com', 'password': 'lobot', 'species': 2, 'bio': "Never far from Baron Administrator Lando Calrissian's side was Lobot, Calrissian's aide and Cloud City's computer liaison officer. Lobot is a human male with a shiny, brain-enhancing device wrapped around the back of his skull that allowed him to contact directly with the city's central computer.",
     'faction': True, 'credits': 25000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/26.jpg', "force_points": 0},
    {'name': 'Admiral Ackbar', 'email': 'ackie@rebels.com', 'password': 'itsatrap', 'species': 8, 'bio': "A veteran commander, Ackbar led the defense of his homeworld, Mon Cala, during the Clone Wars and then masterminded the rebel attack on the second Death Star at the Battle of Endor. Ackbar realized the rebels had been drawn into a trap at Endor, but adjusted, with his fleet buying valuable time for the attack to succeed. ",
     'faction': True, 'credits': 500000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/27.jpg', "force_points": 0},
    {'name': 'Mon Mothma', 'email': 'mon@rebels.com', 'password': 'mothma', 'species': 1, 'bio': "A leader of the Galactic Senate's Loyalist faction, Mon Mothma opposed Supreme Chancellor Palpatine's policies during the final days of the Republic. Working in secret, she helped found the Rebel Alliance, and served as its civilian leader during the long struggle against the Empire.",
     'faction': True, 'credits': 250000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/28.jpg', "force_points": 0},
    {'name': 'Arvel Crynyd', 'email': 'crynyd@rebels.com', 'password': 'nooneknowsme', 'species': 1, 'bio': "Arvel Crynyd was a male human pilot who served in the Alliance to Restore the Republic during the Galactic Civil War. In the war's fourth year, Commander Crynyd participated in the Rebellion's attack on the Galactic Empire's second Death Star in the Battle of Endor, flying an RZ-1 A-wing interceptor in Green Squadron as leader of the squadron",
     'faction': True, 'credits': 120000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/29.jpg', "force_points": 0},
    {'name': 'Wicket Systri Warrick', 'email': 'wicket@emok.org', 'password': 'lublub', 'species': 9, 'bio': "Wicket W. Warrick was the brave young Ewok who willingly joined the Rebellion and aided in the battle against the Empire on the forest moon of Endor. Even before he encountered the Rebels, Wicket had devised methods for defeating the Imperial machines, plans which were implemented after the Ewok befriended Princess Leia and recruited his tribe to the Alliance's cause.",
     'faction': True, 'credits': 50000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/30.jpg', "force_points": 0},
    {'name': 'Nien Nunb', 'email': 'nunb@rebels.com', 'password': 'nubnub', 'species': 10, 'bio': "A native of Sullust, Nien Nunb was a smuggler who fought for both the Rebel Alliance and the Resistance during his long career. An expert pilot, he served as Lando Calrissian’s co-pilot aboard the Millennium Falcon during the Battle of Endor, flew an X-wing in the raid on Starkiller Base and survived the First Order’s assault on Crait.",
     'faction': True, 'credits': 152000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/31.jpg', "force_points": 0},
    {'name': 'Qui-Gon Jinn', 'email': 'quigon@force.net', 'password': 'jedi4life', 'species': 1, 'bio': "A venerable if maverick Jedi Master, Qui-Gon Jinn was a student of the living Force. Qui-Gon lived for the moment, espousing a philosophy of 'feel, don't think -- use your instincts.' On Tatooine, Qui-Gon discovered a young slave boy named Anakin Skywalker who was strong in the Force. Sensing the boy's potential, Qui-Gon liberated Anakin from slavery.",
     'faction': True, 'credits': 555000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/32.jpg', "force_points": 0},
    {'name': 'Watto', 'email': 'watto@ibuyjunk.org', 'password': 'nubian', 'species': 13, 'bio': "Watto was a Toydarian junk dealer in Mos Espa who bought Shmi Skywalker and her son Anakin from Gardulla the Hutt. An inveterate gambler, he sponsored Anakin in several Podraces, but often bet against his own slave, who was talented but inexperienced.",
     'faction': True, 'credits': 237000, 'user_image': 'https://starwars-trader-imgs.s3.us-east-2.amazonaws.com/img/characters/40.jpg', "force_points": 0}
]
transactions = [
    {'buyer': 14, 'seller': 25, 'starship': 1,
        'sale_price': 1000000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 12, 'seller': 21, 'starship': 2,
     'sale_price': 1000000000000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 10, 'seller': 20, 'starship': 3,
     'sale_price': 220000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 4, 'seller': 21, 'starship': 4, 'sale_price': 119999,
     'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 27, 'seller': 28, 'starship': 5,
     'sale_price': 100000000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 22, 'seller': 24, 'starship': 6,
     'sale_price': 249999, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 18, 'seller': 27, 'starship': 7,
     'sale_price': 105000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 21, 'seller': 12, 'starship': 8,
     'sale_price': 157000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 14, 'seller': 4, 'starship': 9, 'sale_price': 251000,
     'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 4, 'seller': 21, 'starship': 10,
     'sale_price': 150000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 25, 'seller': 20, 'starship': 11,
     'sale_price': 430000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 24, 'seller': 22, 'starship': 12,
     'sale_price': 148005, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 17, 'seller': 4, 'starship': 13,
     'sale_price': 224725, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 5, 'seller': 27, 'starship': 14,
     'sale_price': 425000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 31, 'seller': 5, 'starship': 15,
     'sale_price': 625000, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 9, 'seller': 28, 'starship': 16,
     'sale_price': 215999, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 30, 'seller': 21, 'starship': 17,
     'sale_price': 255999, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 33, 'seller': 32, 'starship': 18,
     'sale_price': 182575, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 29, 'seller': 27, 'starship': 19,
     'sale_price': 190500, 'sale_date': datetime.datetime.now().isoformat()},
    {'buyer': 28, 'seller': 11, 'starship': 20,
     'sale_price': 65000, 'sale_date': datetime.datetime.now().isoformat()}
]
